// Kylos IPTV Player - Firebase Initializer
// Handles Firebase initialization at app startup.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:flutter/foundation.dart';

/// Firebase initialization result.
class FirebaseInitResult {
  const FirebaseInitResult({
    required this.success,
    this.error,
  });

  final bool success;
  final String? error;

  factory FirebaseInitResult.success() =>
      const FirebaseInitResult(success: true);

  factory FirebaseInitResult.failure(String error) =>
      FirebaseInitResult(success: false, error: error);
}

/// Handles Firebase initialization and configuration.
///
/// This class encapsulates all Firebase setup logic and provides
/// access to Firebase service instances.
class FirebaseInitializer {
  FirebaseInitializer._();

  static FirebaseInitializer? _instance;

  /// Singleton instance.
  static FirebaseInitializer get instance {
    _instance ??= FirebaseInitializer._();
    return _instance!;
  }

  bool _initialized = false;

  /// Whether Firebase has been initialized.
  bool get isInitialized => _initialized;

  /// Firebase Auth instance.
  FirebaseAuth get auth {
    _ensureInitialized();
    return FirebaseAuth.instance;
  }

  /// Firestore instance.
  FirebaseFirestore get firestore {
    _ensureInitialized();
    return FirebaseFirestore.instance;
  }

  /// Remote Config instance.
  FirebaseRemoteConfig get remoteConfig {
    _ensureInitialized();
    return FirebaseRemoteConfig.instance;
  }

  /// Initializes Firebase services.
  ///
  /// Must be called before any Firebase services are used.
  /// Typically called from bootstrap.dart during app startup.
  ///
  /// The [options] parameter should come from firebase_options.dart
  /// generated by FlutterFire CLI.
  Future<FirebaseInitResult> initialize({
    FirebaseOptions? options,
  }) async {
    if (_initialized) {
      return FirebaseInitResult.success();
    }

    try {
      // Initialize Firebase Core
      await Firebase.initializeApp(options: options);

      // Configure Firestore settings
      _configureFirestore();

      // Configure Remote Config
      await _configureRemoteConfig();

      _initialized = true;

      if (kDebugMode) {
        print('Firebase initialized successfully');
      }

      return FirebaseInitResult.success();
    } on FirebaseException catch (e) {
      final error = 'Firebase initialization failed: ${e.message}';
      if (kDebugMode) {
        print(error);
      }
      return FirebaseInitResult.failure(error);
    } catch (e) {
      final error = 'Unexpected error during Firebase initialization: $e';
      if (kDebugMode) {
        print(error);
      }
      return FirebaseInitResult.failure(error);
    }
  }

  void _configureFirestore() {
    final firestore = FirebaseFirestore.instance;

    // Enable offline persistence for graceful degradation
    firestore.settings = const Settings(
      persistenceEnabled: true,
      cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
    );
  }

  Future<void> _configureRemoteConfig() async {
    final remoteConfig = FirebaseRemoteConfig.instance;

    // Set minimum fetch interval based on build mode
    await remoteConfig.setConfigSettings(
      RemoteConfigSettings(
        fetchTimeout: const Duration(seconds: 10),
        minimumFetchInterval: kDebugMode
            ? const Duration(minutes: 5)
            : const Duration(hours: 12),
      ),
    );

    // Set default values
    await remoteConfig.setDefaults({
      'epg_enabled': true,
      'vod_enabled': true,
      'series_enabled': true,
      'catch_up_enabled': false,
      'multi_audio_enabled': true,
      'subtitles_enabled': true,
      'parental_controls_enabled': true,
      'cloud_sync_enabled': true,
      'new_player_enabled': false,
      'force_update': false,
      'maintenance_mode': false,
      'maintenance_message': '',
      'min_app_version_android': '1.0.0',
      'min_app_version_ios': '1.0.0',
      'min_app_version_android_tv': '1.0.0',
    });

    // Fetch and activate on startup (non-blocking)
    remoteConfig.fetchAndActivate().catchError((e) {
      if (kDebugMode) {
        print('Remote config fetch failed: $e');
      }
      return false;
    });
  }

  void _ensureInitialized() {
    if (!_initialized) {
      throw StateError(
        'Firebase has not been initialized. '
        'Call FirebaseInitializer.instance.initialize() first.',
      );
    }
  }

  /// Resets the initializer for testing purposes.
  @visibleForTesting
  static void reset() {
    _instance = null;
  }
}
